### ISSUE TITLE
Hacktoberfest Swags

### ISSUE THREAD

**Issue by kaggrwal** [docker/hacktoberfest-2022#65]
Hi Team,

Where can we apply/redeem the swags for the PRs that have been merged for docker extensions during Hacktoberfest 2022.?

**Comment by AlbaRoza** [comment]
Hi @kaggrwal , could you please share the link of the PR you're mentioning?

Thanks!

**Comment by kaggrwal** [comment]
> Hi @kaggrwal , could you please share the link of the PR you're mentioning?
> 
> Thanks!

sure @AlbaRoza , please find below the link for the same:

https://github.com/loopDelicious/docker-extension/pull/7

Thanks!

**Comment by heysagnik** [comment]
Hi @AlbaRoza I have the same doubt , my pr link is [this](https://github.com/n-murphy/swagger-editor-docker-extension/pull/10)

**Comment by AlbaRoza** [comment]
Hi @kaggrwal and @heysagnik, thank you for your participation in Hacktoberfest 2022. We'll be announcing our winners on **Tuesday, November the 15th**. That same day we'll contact the successful contributors to get their postal addresses and give them more information about the swag.

Have a great day!

**Comment by kaggrwal** [comment]
@AlbaRoza There is no communication regarding swags, please check.
